// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {context} from '../models';

export function AddContent(arg1:app.ClipContent):Promise<void>;

export function GetContents():Promise<{[key: string]: app.ClipContent}>;

export function StartUp(arg1:context.Context):Promise<void>;
