// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddContent(arg1) {
  return window['go']['app']['Clipboard']['AddContent'](arg1);
}

export function GetContents() {
  return window['go']['app']['Clipboard']['GetContents']();
}

export function StartUp(arg1) {
  return window['go']['app']['Clipboard']['StartUp'](arg1);
}
