// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Get(arg1) {
  return window['go']['app']['Config']['Get'](arg1);
}

export function GetAll() {
  return window['go']['app']['Config']['GetAll']();
}

export function Set(arg1, arg2) {
  return window['go']['app']['Config']['Set'](arg1, arg2);
}

export function StartUp(arg1) {
  return window['go']['app']['Config']['StartUp'](arg1);
}
