// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {context} from '../models';

export function Get(arg1:string):Promise<any>;

export function GetAll():Promise<app.cfg>;

export function Set(arg1:string,arg2:any):Promise<void>;

export function StartUp(arg1:context.Context):Promise<void>;
