// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GreetMe(arg1) {
  return window['go']['main']['App']['GreetMe'](arg1);
}
